# distributed training
nodes: 1
gpus: 4
nr: 0
dataparallel: 0
workers: 8
visible_gpus: "4,5,6,7"

# Paths
data_path: "/home/r20user17/MCL/data/splits/gbmlgg15cv_all_st_0_0_0.pkl"
checkpoints: "./checkpoints"

# Dataset Options
dataset: "TCGA"

# Model options
pretrained: False
reload: False

# training options
seed: 42
batch_size: 8
image_size: 1024
start_epoch: 0
epochs: 100
lr: 0.0001
lambda_gene: 50
