# distributed training
nodes: 1
gpus: 4
nr: 0
dataparallel: 0
workers: 8
visible_gpus: "4,5,6,7"

# Paths
data_path: "./data/splits/gbmlgg15cv_all_st_0_0_0.pkl"
checkpoints: "./checkpoints"

# Dataset Options
dataset: "TCGA"

# Model options
pretrained: ""
reload: False

# training options
seed: 42
batch_size: 3
image_size: 1024
start_epoch: 0
epochs: 500
warmup_epochs: -1
lr: 0.001
lambda_gene: 5000
lambda_region: 1
threshold: 0.5
temperature: 0.5
