# distributed training
nodes: 1
gpus: 4
nr: 0
dataparallel: 0
workers: 8
visible_gpus: "0,1,2,3"

# Paths
data_path: "./data/splits/my_split_dropGradeNaN.pkl"
checkpoints: "./checkpoints"

# Dataset Options
dataset: "TCGA"

# Model options
pretrained: ""
reload: False
ema: True
gene: ['PTEN', '10q', 'EGFR', '10p', '7p', 'idh mutation', 'CARD11', '7q', 'FGFR2', 'CREB3L2']

# training options
seed: 42
batch_size: 28
image_size: 1024
start_epoch: 0
epochs: 100
ema_decay: 0.999
lr: 0.0001
lambda_gene: 5000
lambda_region: 0.2
threshold: 0.5
temperature: 0.5
