# distributed training
nodes: 1
gpus: 4
nr: 0
dataparallel: 0
workers: 8
visible_gpus: "4,5,6,7"

# Paths
data_path: "./my_split_dropGradeNaN.pkl"
checkpoints: "./checkpoints"

# Dataset Options
dataset: "TCGA"
subset: "dropGradNaN"

# Model options
pretrained: ""
dis_gene: ['idh mutation', 'codeletion', 'PTEN', 'EGFR', 'CARD11', 'FGFR2']
float_gene: ['10q', '10p', '7p', '7q']
patch_size: 16
window_size: 7

# training options
seed: 42
batch_size: 1
image_size: 1024
epochs: 300
ema_decay: 0.999
lr: 1.0e-5
lambda_float_gene: 5
lambda_dis_gene: 0.2
lambda_region: 0.2
threshold: 0.4
temperature: 0.07
