# distributed training
nodes: 1
gpus: 4
nr: 0
dataparallel: 0
workers: 8
visible_gpus: "0,1,2,3"

# Paths
data_path: "./data/splits/my_split_dropGradeNaN.pkl"
checkpoints: "./checkpoints"

# Dataset Options
dataset: "TCGA"

# Model options
pretrained: ""
dis_gene: ['idh mutation', 'codeletion', 'PTEN', 'EGFR', 'CARD11', 'FGFR2']
float_gene: ['10q', '10p', '7p', '7q', '20p', '20q']
patch_size: 16
window_size: 7

# training options
seed: 42
batch_size: 16
image_size: 1024
warmup: 10
epochs: 100
ema_decay: 0.999
lr: 0.0008
lambda_float_gene: 500
lambda_dis_gene: 0.02
lambda_region: 0.2
threshold: 0.5
temperature: 0.5
